# Generated by Django 4.0.4 on 2022-05-25 14:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('carrentapp', '0002_remove_order_car_brand_remove_order_car_model_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='issue_resolved',
            field=models.BooleanField(null=True, verbose_name='Problem rozwiązany'),
        ),
    ]
