# Generated by Django 4.0.4 on 2022-05-27 12:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('carrentapp', '0003_order_issue_resolved'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='kilometers_traveled',
            field=models.IntegerField(null=True, verbose_name='Przejechane kilometry'),
        ),
    ]
