# Generated by Django 4.0.4 on 2022-06-01 14:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('carrentapp', '0004_order_kilometers_traveled'),
    ]

    operations = [
        migrations.AlterField(
            model_name='car',
            name='engine_type',
            field=models.CharField(choices=[('PE', 'Benzynowy'), ('DI', 'Diesel'), ('EL', 'Elektryczny'), ('HY', 'Hybryda')], max_length=20, verbose_name='Rodzaj silnika'),
        ),
        migrations.AlterField(
            model_name='order',
            name='kilometers_traveled',
            field=models.IntegerField(default=0, verbose_name='Przejechane kilometry'),
        ),
    ]
