# Generated by Django 4.0.4 on 2022-07-05 14:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('carrentapp', '0005_alter_car_engine_type_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='BaseUserDiscount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('max_discount', models.IntegerField(verbose_name='Maksymalna zniżka')),
                ('increment_per_tick', models.IntegerField(verbose_name='Skok zniżki')),
                ('orders_per_tick', models.IntegerField(verbose_name='Co ile zamówień skok')),
                ('min_order_length', models.IntegerField(verbose_name='Minimalna długość zamówienia')),
            ],
        ),
        migrations.CreateModel(
            name='TimeDiscount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('month_discount', models.IntegerField(verbose_name='Zniżka miesięczna')),
                ('two_weeks_discount', models.IntegerField(verbose_name='Zniżka dwutygodniowa')),
            ],
        ),
        migrations.AddField(
            model_name='order',
            name='order_length',
            field=models.IntegerField(default=0, verbose_name='Długość wypożyczenia'),
        ),
        migrations.AlterField(
            model_name='car',
            name='color',
            field=models.CharField(max_length=20, verbose_name='Kolor'),
        ),
        migrations.AlterField(
            model_name='car',
            name='engine_type',
            field=models.CharField(choices=[('PE', 'Benzynowy'), ('DI', 'Diesel'), ('EL', 'Elektryczny'), ('HY', 'Hybryda')], max_length=2, verbose_name='Rodzaj silnika'),
        ),
        migrations.AlterField(
            model_name='car',
            name='gearbox_type',
            field=models.CharField(choices=[('A', 'Automatyczna'), ('M', 'Manualna')], max_length=1, verbose_name='Skrzynia biegów'),
        ),
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('A', 'Aktywny'), ('H', 'Historia')], default='A', max_length=1, verbose_name='Status'),
        ),
        migrations.CreateModel(
            name='CarDiscount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('brand_discount', models.IntegerField(verbose_name='Zniżka na marke')),
                ('car_brand', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='carrentapp.carbrand')),
            ],
        ),
    ]
