# Generated by Django 4.0.4 on 2022-07-06 10:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('carrentapp', '0006_baseuserdiscount_timediscount_order_order_length_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='CarDiscount',
            new_name='BrandDiscount',
        ),
    ]
